/**
 * @file test_interop.c
 * @brief Interoperability test for carquet
 *
 * Reads Parquet files generated by other libraries and verifies they can be
 * parsed AND fully decoded. Two modes:
 *
 *   --dir <directory>   Strict batch-decode of every .parquet file in a tree.
 *                       Returns non-zero if any file fails to fully decode.
 *   --json <file>       Emit a JSON summary of one file's decoded contents
 *                       (row/column counts + first values per column) for the
 *                       Python harness to cross-check against an oracle
 *                       (PyArrow). Always exits 0 on a clean decode, 1 on a
 *                       clean read error (prints {"ok":false,...}); a crash
 *                       shows up to the caller as a signal.
 *
 * Build:
 *   gcc -I../include -o test_interop test_interop.c ../build/libcarquet.a
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <dirent.h>
#include <sys/stat.h>
#include <carquet/carquet.h>

#define CARQUET_END_OF_DATA 63   /* status returned when the stream is drained */
#define JSON_FIRST_N 5           /* values emitted/compared per column         */

typedef struct {
    int files_tested;
    int files_passed;
    int files_failed;
} test_stats_t;

/* ── Strict decode (--dir) ──────────────────────────────────────────────────
 *
 * A file passes only if it opens, exposes a schema, and the batch reader
 * decodes exactly num_rows values for every column with no per-column read
 * error and a clean END_OF_DATA termination. Metadata-only "PARTIAL" passes
 * (the old behavior) are gone: a file that cannot be fully decoded fails.
 */
static int test_file(const char* path, int verbose) {
    carquet_error_t err = CARQUET_ERROR_INIT;

    if (verbose) {
        printf("\n=== Testing: %s ===\n", path);
    }

    carquet_reader_options_t opts;
    carquet_reader_options_init(&opts);
    opts.use_mmap = true;

    carquet_reader_t* reader = carquet_reader_open(path, &opts, &err);
    if (!reader) {
        if (verbose) printf("  FAIL: open: %s\n", err.message);
        return 1;
    }

    int64_t num_rows = carquet_reader_num_rows(reader);
    int32_t num_cols = carquet_reader_num_columns(reader);

    const carquet_schema_t* schema = carquet_reader_schema(reader);
    if (!schema) {
        if (verbose) printf("  FAIL: no schema\n");
        carquet_reader_close(reader);
        return 1;
    }

    carquet_batch_reader_config_t config;
    carquet_batch_reader_config_init(&config);
    config.batch_size = 10000;

    carquet_batch_reader_t* br = carquet_batch_reader_create(reader, &config, &err);
    if (!br) {
        if (verbose) printf("  FAIL: batch reader: %s\n", err.message);
        carquet_reader_close(reader);
        return 1;
    }

    int rc = 0;
    int64_t total = 0;
    carquet_row_batch_t* batch = NULL;
    carquet_status_t st;
    while ((st = carquet_batch_reader_next(br, &batch)) == CARQUET_OK && batch) {
        int64_t batch_rows = carquet_row_batch_num_rows(batch);
        for (int32_t c = 0; c < num_cols; c++) {
            const void* data;
            const uint8_t* nulls;
            int64_t n;
            if (carquet_row_batch_column(batch, c, &data, &nulls, &n) != CARQUET_OK) {
                if (verbose) printf("  FAIL: column %d read error\n", c);
                rc = 1;
            }
        }
        total += batch_rows;
        carquet_row_batch_free(batch);
        batch = NULL;
    }
    if (st != CARQUET_OK && st != CARQUET_END_OF_DATA) {
        if (verbose) printf("  FAIL: next() status %d\n", st);
        rc = 1;
    }
    if (total != num_rows) {
        if (verbose) printf("  FAIL: decoded %lld rows, expected %lld\n",
                            (long long)total, (long long)num_rows);
        rc = 1;
    }

    carquet_batch_reader_free(br);
    carquet_reader_close(reader);

    if (verbose && rc == 0) printf("  PASS (%lld rows)\n", (long long)num_rows);
    return rc;
}

/* ── JSON emit (--json) ─────────────────────────────────────────────────────*/

static void json_emit_string(const char* s, int32_t len) {
    putchar('"');
    for (int32_t i = 0; i < len; i++) {
        unsigned char ch = (unsigned char)s[i];
        if (ch == '"' || ch == '\\') { putchar('\\'); putchar(ch); }
        else if (ch == '\n') { fputs("\\n", stdout); }
        else if (ch < 0x20)  { printf("\\u%04x", ch); }
        else putchar(ch);
    }
    putchar('"');
}

static void json_emit_hex(const uint8_t* p, int32_t len) {
    putchar('"');
    for (int32_t i = 0; i < len; i++) printf("%02x", p[i]);
    putchar('"');
}

static const char* physical_type_str(carquet_physical_type_t t) {
    switch (t) {
        case CARQUET_PHYSICAL_BOOLEAN: return "BOOLEAN";
        case CARQUET_PHYSICAL_INT32: return "INT32";
        case CARQUET_PHYSICAL_INT64: return "INT64";
        case CARQUET_PHYSICAL_INT96: return "INT96";
        case CARQUET_PHYSICAL_FLOAT: return "FLOAT";
        case CARQUET_PHYSICAL_DOUBLE: return "DOUBLE";
        case CARQUET_PHYSICAL_BYTE_ARRAY: return "BYTE_ARRAY";
        case CARQUET_PHYSICAL_FIXED_LEN_BYTE_ARRAY: return "FLBA";
    }
    return "UNKNOWN";
}

/* Emit one logical row's value for a column. Nulls -> JSON null; FLBA/INT96 ->
 * a "<bin>" sentinel the oracle skips (their length is not available here). */
static void json_emit_value(carquet_physical_type_t t, const void* data,
                            const uint8_t* nulls, int64_t i) {
    int is_null = nulls && !(nulls[i / 8] & (1u << (i % 8)));
    if (is_null) { fputs("null", stdout); return; }

    switch (t) {
        case CARQUET_PHYSICAL_BOOLEAN:
            fputs(((const uint8_t*)data)[i] ? "true" : "false", stdout); break;
        case CARQUET_PHYSICAL_INT32:
            printf("%d", ((const int32_t*)data)[i]); break;
        case CARQUET_PHYSICAL_INT64:
            printf("%lld", (long long)((const int64_t*)data)[i]); break;
        case CARQUET_PHYSICAL_FLOAT: {
            float v = ((const float*)data)[i];
            if (isnan(v) || isinf(v)) fputs("null", stdout);
            else printf("%.9g", (double)v);
            break;
        }
        case CARQUET_PHYSICAL_DOUBLE: {
            double v = ((const double*)data)[i];
            if (isnan(v) || isinf(v)) fputs("null", stdout);
            else printf("%.17g", v);
            break;
        }
        case CARQUET_PHYSICAL_BYTE_ARRAY: {
            const carquet_byte_array_t* ba = (const carquet_byte_array_t*)data + i;
            json_emit_hex(ba->data, ba->length);
            break;
        }
        case CARQUET_PHYSICAL_FIXED_LEN_BYTE_ARRAY:
        case CARQUET_PHYSICAL_INT96:
        default:
            fputs("\"<bin>\"", stdout); break;
    }
}

static int emit_json(const char* path) {
    carquet_error_t err = CARQUET_ERROR_INIT;
    carquet_reader_options_t opts;
    carquet_reader_options_init(&opts);
    opts.use_mmap = true;

    carquet_reader_t* reader = carquet_reader_open(path, &opts, &err);
    if (!reader) {
        printf("{\"ok\":false,\"error\":");
        json_emit_string(err.message, (int32_t)strlen(err.message));
        printf("}\n");
        return 1;
    }

    int64_t num_rows = carquet_reader_num_rows(reader);
    int32_t num_cols = carquet_reader_num_columns(reader);
    const carquet_schema_t* schema = carquet_reader_schema(reader);

    carquet_batch_reader_config_t config;
    carquet_batch_reader_config_init(&config);
    config.batch_size = JSON_FIRST_N > 0 ? JSON_FIRST_N : 1;

    carquet_batch_reader_t* br = carquet_batch_reader_create(reader, &config, &err);
    carquet_row_batch_t* batch = NULL;
    if (br) (void)carquet_batch_reader_next(br, &batch);

    printf("{\"ok\":true,\"num_rows\":%lld,\"num_columns\":%d,\"columns\":[",
           (long long)num_rows, num_cols);

    for (int32_t c = 0; c < num_cols; c++) {
        if (c) putchar(',');
        const char* name = carquet_schema_column_name(schema, c);
        carquet_physical_type_t ptype = carquet_schema_column_type(schema, c);
        printf("{\"name\":");
        json_emit_string(name ? name : "", name ? (int32_t)strlen(name) : 0);
        printf(",\"type\":\"%s\",\"first\":[", physical_type_str(ptype));

        const void* data = NULL;
        const uint8_t* nulls = NULL;
        int64_t n = 0;
        int have = batch &&
            carquet_row_batch_column(batch, c, &data, &nulls, &n) == CARQUET_OK;
        int64_t emit = !have ? 0 : (n < JSON_FIRST_N ? n : JSON_FIRST_N);
        for (int64_t i = 0; i < emit; i++) {
            if (i) putchar(',');
            json_emit_value(ptype, data, nulls, i);
        }
        printf("]}");
    }
    printf("]}\n");

    if (batch) carquet_row_batch_free(batch);
    if (br) carquet_batch_reader_free(br);
    carquet_reader_close(reader);
    return 0;
}

/* ── Directory walk ─────────────────────────────────────────────────────────*/

static int test_directory(const char* dir_path, test_stats_t* stats, int verbose) {
    DIR* dir = opendir(dir_path);
    if (!dir) { perror("opendir"); return 1; }

    struct dirent* entry;
    while ((entry = readdir(dir)) != NULL) {
        if (entry->d_name[0] == '.') continue;

        char path[4096];
        snprintf(path, sizeof(path), "%s/%s", dir_path, entry->d_name);

        struct stat sb;
        if (stat(path, &sb) != 0) continue;

        if (S_ISDIR(sb.st_mode)) {
            test_directory(path, stats, verbose);
        } else if (S_ISREG(sb.st_mode)) {
            const char* ext = strrchr(entry->d_name, '.');
            if (ext && strcmp(ext, ".parquet") == 0) {
                stats->files_tested++;
                if (test_file(path, verbose) == 0) {
                    stats->files_passed++;
                    if (!verbose) printf(".");
                } else {
                    stats->files_failed++;
                    if (!verbose) printf("F");
                }
                fflush(stdout);
            }
        }
    }
    closedir(dir);
    return 0;
}

int main(int argc, char** argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <parquet_file>\n", argv[0]);
        fprintf(stderr, "       %s --dir <directory> [-v]\n", argv[0]);
        fprintf(stderr, "       %s --json <file>\n", argv[0]);
        return 1;
    }

    if (carquet_init() != CARQUET_OK) {
        fprintf(stderr, "Failed to initialize carquet\n");
        return 1;
    }

    int verbose = 0;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-v") == 0 || strcmp(argv[i], "--verbose") == 0)
            verbose = 1;
    }

    if (strcmp(argv[1], "--json") == 0) {
        if (argc < 3) { fprintf(stderr, "--json requires a file\n"); return 1; }
        return emit_json(argv[2]);
    }

    if (strcmp(argv[1], "--dir") == 0) {
        if (argc < 3) { fprintf(stderr, "--dir requires a directory\n"); return 1; }
        test_stats_t stats = {0, 0, 0};
        printf("Testing all .parquet files in: %s\n", argv[2]);
        if (!verbose) printf("Progress: ");
        test_directory(argv[2], &stats, verbose);
        printf("\n\n=== Summary ===\n");
        printf("Files tested: %d\n", stats.files_tested);
        printf("Passed: %d\n", stats.files_passed);
        printf("Failed: %d\n", stats.files_failed);
        return stats.files_failed > 0 ? 1 : 0;
    }

    return test_file(argv[1], 1);
}
